import { use } from "react"
import './../scss/main.scss'
import Header from './_components/Layout/Header'
import Footer from './_components/Layout/Footer'
import HeroSection from './_components/HeroSection'
import InfoBlock from './_components/InfoBlock'
import '../scss/main.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header /> 
       
        {children}
        <Footer />
        </body>
    </html>
  )
}
